# Generated by Django 5.1 on 2024-08-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideElement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idVersion', models.BigIntegerField()),
                ('elementCode', models.CharField(max_length=100)),
                ('elementValue', models.CharField(max_length=300)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idVersion', 'elementCode'), name='unique_idVersion_elementCode')],
            },
        ),
        migrations.CreateModel(
            name='GuideVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idGuide', models.BigIntegerField()),
                ('version', models.CharField(max_length=50)),
                ('dateStart', models.DateField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('idGuide', 'version'), name='unique_idGuide_version'), models.UniqueConstraint(fields=('idGuide', 'dateStart'), name='unique_idGuide_dateStart')],
            },
        ),
    ]
