# Generated by Django 5.1 on 2024-08-29 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_guideelement_idversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guide',
            options={'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='guideelement',
            options={'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочников'},
        ),
        migrations.AlterModelOptions(
            name='guideversion',
            options={'verbose_name': 'Версия справочника', 'verbose_name_plural': 'Версии справочников'},
        ),
    ]
