# Generated by Django 5.1 on 2024-09-01 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_guideversion_unique_idguide_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideelement',
            name='elementCode',
            field=models.CharField(max_length=100, verbose_name='Код элемента'),
        ),
        migrations.AlterField(
            model_name='guideelement',
            name='elementValue',
            field=models.CharField(max_length=300, verbose_name='Значение элемента'),
        ),
        migrations.AlterField(
            model_name='guideelement',
            name='idVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guideversion', verbose_name='Идентификатор версии'),
        ),
        migrations.AlterField(
            model_name='guideversion',
            name='codeGuide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guide', to_field='code', verbose_name='Код справочника'),
        ),
    ]
