# Generated by Django 5.1 on 2024-09-01 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_guideelement_elementcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideelement',
            name='idVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guideversion', verbose_name='Код, наименование справочника и значение версии'),
        ),
        migrations.AlterField(
            model_name='guideversion',
            name='codeGuide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guide', to_field='code', verbose_name='Код справочника и его наименование'),
        ),
        migrations.AlterField(
            model_name='guideversion',
            name='dateStart',
            field=models.DateField(blank=True, verbose_name='Дата начала версии'),
        ),
    ]
