# Generated by Django 5.1 on 2024-09-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_guideelement_idversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideversion',
            name='codeGuide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.guide', verbose_name='Код справочника и его наименование'),
        ),
    ]
